webtalk_init -webtalk_dir /home/luiz/Documentos/UnB/PED2/Lab2/projeto_rtl/mediaRTL/mediaRTL.sim/sim_1/behav/xsim/xsim.dir/tb_rtl_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Sep 20 22:40:00 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e394ddbd-01b9-4332-bbfa-c29199de4b75" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f0972cf349314e3ca5c4624bc470e2aa" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "350" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1400.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "123536_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3171679692 -regid "" -xml /home/luiz/Documentos/UnB/PED2/Lab2/projeto_rtl/mediaRTL/mediaRTL.sim/sim_1/behav/xsim/xsim.dir/tb_rtl_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/luiz/Documentos/UnB/PED2/Lab2/projeto_rtl/mediaRTL/mediaRTL.sim/sim_1/behav/xsim/xsim.dir/tb_rtl_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/luiz/Documentos/UnB/PED2/Lab2/projeto_rtl/mediaRTL/mediaRTL.sim/sim_1/behav/xsim/xsim.dir/tb_rtl_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
