#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Sep 20 21:06:47 -03 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_rtl_behav -key {Behavioral:sim_1:Functional:tb_rtl} -tclbatch tb_rtl.tcl -view /home/luiz/Documentos/UnB/PED2/Lab2/projeto_rtl/mediaRTL/tb_rtl_behav.wcfg -log simulate.log"
xsim tb_rtl_behav -key {Behavioral:sim_1:Functional:tb_rtl} -tclbatch tb_rtl.tcl -view /home/luiz/Documentos/UnB/PED2/Lab2/projeto_rtl/mediaRTL/tb_rtl_behav.wcfg -log simulate.log

